spring:
  application:
    name: smart-agriculture-backend

  datasource:
    url: jdbc:mysql://localhost:3309/smart_agriculture?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: smart-agriculture-secret-key-change-this
  expire-hours: 24

hardware:
  control:
    enabled: true
    base-url: http://192.168.20.84:3000
    device: bearpi_001

mqtt:
  enabled: true
  broker-url: tcp://127.0.0.1:1883
  client-id: smart-agriculture-backend
  username: fasong
  password: fasong123
  qos: 1
  topics:
    telemetry: device/data/upload
    heartbeat: device/heartbeat
    control: device/control/cmd
    control-reply: device/control/reply

pest:
  model:
    enabled: true
    url: http://127.0.0.1:5002/api/ai/pest/analyze
    token: ${AI_SERVICE_TOKEN:}
    connect-timeout-seconds: 5
    read-timeout-seconds: 240

ai:
  chat:
    model:
      enabled: true
      url: http://127.0.0.1:5002/api/ai/chat
      token: ${AI_SERVICE_TOKEN:}
      connect-timeout-seconds: 5
      read-timeout-seconds: 240

face:
  model:
    enabled: true
    url: http://127.0.0.1:5001
    connect-timeout-seconds: 5
    read-timeout-seconds: 30
