CREATE DATABASE IF NOT EXISTS smart_agriculture
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE smart_agriculture;

CREATE TABLE IF NOT EXISTS user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50),
  role VARCHAR(20) DEFAULT 'USER',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  crop_type VARCHAR(50),
  location VARCHAR(100),
  area DECIMAL(10,2),
  status VARCHAR(20) DEFAULT 'ONLINE',
  description VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS device (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_code VARCHAR(50) NOT NULL UNIQUE,
  device_name VARCHAR(100) NOT NULL,
  device_type VARCHAR(50) NOT NULL,
  plot_id BIGINT,
  status VARCHAR(20) DEFAULT 'OFFLINE',
  last_heartbeat DATETIME,
  signal_strength INT,
  battery INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plot_id BIGINT NOT NULL,
  device_id BIGINT,
  soil_moisture DECIMAL(5,2),
  air_temperature DECIMAL(5,2),
  air_humidity DECIMAL(5,2),
  illuminance DECIMAL(10,2),
  pump_status VARCHAR(20),
  light_status VARCHAR(20),
  collected_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS control_command (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  command_no VARCHAR(50) NOT NULL UNIQUE,
  plot_id BIGINT,
  device_id BIGINT,
  device_code VARCHAR(50) NOT NULL,
  command_type VARCHAR(50) NOT NULL,
  command_value VARCHAR(100),
  status VARCHAR(20) DEFAULT 'PENDING',
  request_source VARCHAR(20) DEFAULT 'WEB',
  error_message VARCHAR(255),
  sent_at DATETIME,
  ack_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS irrigation_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plot_id BIGINT,
  device_id BIGINT,
  device_code VARCHAR(50),
  command_id BIGINT,
  start_time DATETIME NOT NULL,
  end_time DATETIME,
  duration_seconds INT,
  water_amount DECIMAL(10,2),
  status VARCHAR(20) DEFAULT 'RUNNING',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
